spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox_poc
    username: postgres
    password: toor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'false'
    hibernate:
      ddl-auto: update

kafka:
  brokers: localhost:59092
